server:
  port: 8081

solace:
  jms:
    host: smf://localhost:55555
    msgVpn: default
  target:
    queue: job_queue
    topic: tier/hund/puddel
    rpc: rpc_topic

spring:
  jms:
    template:
      receive-timeout: 2000

#spring:
#  jms:
#    pub-sub-domain: true